logging:
  level:
    dev.tindersamurai.prokurator: DEBUG

spring:

  servlet:
    multipart:
      max-request-size: '150MB'
      max-file-size: '150MB'

  datasource:
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: create-drop

  cache:
    cache-names: [user, guilds]
    caffeine:
      spec: maximumSize=10000,expireAfterWrite=60s
